### ISSUE TITLE
DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by sidul001** [GeorgeSheppard/Robotics#94]
I have followed the steps listed, but when I try to import the library i am getting the following error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-5a1ae27dd4b8> in <module>()
----> 1 import qi
      2 import argparse
      3 import sys
      4 import time

C:\Users\artmed\Anaconda3\envs\nao2\lib\site-packages\qi\__init__.py in <module>()
     70 _on_import_module()
     71 
---> 72 from _qi import Application as _Application
     73 from _qi import ApplicationSession as _ApplicationSession
     74 from _qi import ( FutureState, FutureTimeout, Future, Promise,

ImportError: DLL load failed: %1 is not a valid Win32 application.

Would you happen to know how to fix it?

Also, where do I store SDK files? Where should I extract the files?

**Comment by GeorgeSheppard** [comment]
Sorry that looks like an error with the package not any of my code, so I'd recommend looking either at http://doc.aldebaran.com/2-5/dev/python/install_guide.html if you haven't seen that already, or posting it on a more relevant page. Happy to help with any code issues in the repository though.
